# Generated by Django 4.2.2 on 2023-11-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricechart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.IntegerField(blank=True, null=True)),
                ('shopusername', models.CharField(blank=True, max_length=255, null=True)),
                ('shopname', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('fruits', models.BooleanField(default=False, verbose_name='Fruits')),
                ('vegetables', models.BooleanField(default=False, verbose_name='Vegetables')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_perkg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
