# Generated by Django 4.2.2 on 2023-11-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarmapp', '0002_pricechart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerid', models.IntegerField(blank=True, null=True)),
                ('farmerusername', models.CharField(blank=True, max_length=255, null=True)),
                ('farmername', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('fruits', models.BooleanField(default=False, verbose_name='Fruits')),
                ('vegetables', models.BooleanField(default=False, verbose_name='Vegetables')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
