# Generated by Django 4.2.2 on 2023-11-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarmapp', '0003_productchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerid', models.IntegerField(blank=True, null=True)),
                ('farmerusername', models.CharField(blank=True, max_length=255, null=True)),
                ('farmername', models.CharField(blank=True, max_length=255, null=True)),
                ('shopid', models.IntegerField(blank=True, null=True)),
                ('shopusername', models.CharField(blank=True, max_length=255, null=True)),
                ('shopname', models.CharField(blank=True, max_length=255, null=True)),
                ('fruits', models.BooleanField(default=False, verbose_name='Fruits')),
                ('vegetables', models.BooleanField(default=False, verbose_name='Vegetables')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('farmer_accept', models.BooleanField(default=False, verbose_name='Farmer Accept')),
                ('shop_accept', models.BooleanField(default=False, verbose_name='Shop Accept')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_paid', models.BooleanField(default=False, verbose_name='Amount Paid')),
                ('amount_received', models.BooleanField(default=False, verbose_name='Amount Received')),
                ('farmer_delivered', models.BooleanField(default=False, verbose_name='Farmer Delivered')),
                ('shop_received', models.BooleanField(default=False, verbose_name='Shop Received')),
            ],
        ),
    ]
